spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update # ou create, dependendo do que você precisa
    show-sql: true # opcional, mas útil para depuração

server:
  address: 0.0.0.0
  port: 8080

